# Generated by Django 6.0.4 on 2026-04-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0005_alter_estudiante_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
